#!/bin/bash
# /etc/init.d/daemonserver

### BEGIN INIT INFO
# Provides:          daemonserver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a servo
### END INIT INFO


case "$1" in 
    start)
        echo "Starting Daemonserver"
        /home/root/server
        ;;
    stop)
        echo "Stopping servoblaster"
        killall server
        ;;
    *)
        echo "Usage: /etc/init.d/daemonserver start|stop"
        exit 1
        ;;
esac

exit 0
