#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mica.Droid.Resource", IsApplication=true)]

namespace Mica.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Mica.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Mica.Droid.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroidN.Resource.String.ApplicationName = global::Mica.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroidN.Resource.String.Hello = global::Mica.Droid.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_in = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_out = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_right = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int slide_up = 2130968580;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06000b
			public const int aqua = 2131099659;
			
			// aapt resource value: 0x7f060011
			public const int black = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int blue = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int dark_grey = 2131099666;
			
			// aapt resource value: 0x7f060004
			public const int fuchsia = 2131099652;
			
			// aapt resource value: 0x7f06000e
			public const int green = 2131099662;
			
			// aapt resource value: 0x7f060007
			public const int grey = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int lime = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int maroon = 2131099658;
			
			// aapt resource value: 0x7f060010
			public const int navy = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int olive = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int purple = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int red = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int silver = 2131099654;
			
			// aapt resource value: 0x7f06000d
			public const int teal = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int theme_blue = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int theme_green = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int white = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int yellow = 2131099651;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int agenda = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int asistencia = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bombillo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bombillo_amarillo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bombillo_negro = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ButtonSignStyle = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int camara = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int camara_blanca = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int casa = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int casa_domotica = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int casa_domoticaa = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int check_door = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int check_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int crear = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int EditTextStyle = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int facebook = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int google = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int info = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int invitaciones = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int jardin = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Logo = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int mica = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ProgressBarStyle = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int puerta = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int puerta_abierta = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int puerta_cerrada = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int silueta = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int silueta_blanca = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080020
			public const int bottomtoolbarmain = 2131230752;
			
			// aapt resource value: 0x7f08000e
			public const int btnAbout = 2131230734;
			
			// aapt resource value: 0x7f080027
			public const int btnCamera = 2131230759;
			
			// aapt resource value: 0x7f08000f
			public const int btnCloseApp = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int btnDeleteDB2 = 2131230736;
			
			// aapt resource value: 0x7f080029
			public const int btnDoor = 2131230761;
			
			// aapt resource value: 0x7f080003
			public const int btnDoor1 = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int btnDoor2 = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int btnDoor3 = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int btnDoor4 = 2131230726;
			
			// aapt resource value: 0x7f080033
			public const int btnEmailRegister = 2131230771;
			
			// aapt resource value: 0x7f08003e
			public const int btnFinishRegisterPhoto = 2131230782;
			
			// aapt resource value: 0x7f08002d
			public const int btnHouse = 2131230765;
			
			// aapt resource value: 0x7f080008
			public const int btnImageEditProfile = 2131230728;
			
			// aapt resource value: 0x7f08002f
			public const int btnInfo = 2131230767;
			
			// aapt resource value: 0x7f08002b
			public const int btnLight = 2131230763;
			
			// aapt resource value: 0x7f080011
			public const int btnLight1 = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int btnLight2 = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int btnLight3 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int btnLight4 = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int btnLight5 = 2131230741;
			
			// aapt resource value: 0x7f08001c
			public const int btnLogIn = 2131230748;
			
			// aapt resource value: 0x7f080001
			public const int btnNewPhoto = 2131230721;
			
			// aapt resource value: 0x7f080036
			public const int btnNextRegisterEmail = 2131230774;
			
			// aapt resource value: 0x7f08003a
			public const int btnNextRegisterInfo = 2131230778;
			
			// aapt resource value: 0x7f080017
			public const int btnOffLights = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int btnOnLights = 2131230742;
			
			// aapt resource value: 0x7f08000b
			public const int btnReadyEditProfile = 2131230731;
			
			// aapt resource value: 0x7f08001d
			public const int btnRegister = 2131230749;
			
			// aapt resource value: 0x7f08003d
			public const int btnRegisterSelectPhoto = 2131230781;
			
			// aapt resource value: 0x7f080031
			public const int btnSignInFacebook = 2131230769;
			
			// aapt resource value: 0x7f080032
			public const int btnSignInGmail = 2131230770;
			
			// aapt resource value: 0x7f080024
			public const int container = 2131230756;
			
			// aapt resource value: 0x7f080023
			public const int content = 2131230755;
			
			// aapt resource value: 0x7f080025
			public const int footer = 2131230757;
			
			// aapt resource value: 0x7f080022
			public const int header = 2131230754;
			
			// aapt resource value: 0x7f080000
			public const int imageViewCamera = 2131230720;
			
			// aapt resource value: 0x7f08000c
			public const int imageViewEmail = 2131230732;
			
			// aapt resource value: 0x7f080021
			public const int main_content = 2131230753;
			
			// aapt resource value: 0x7f08003f
			public const int progressBarEmailSignIn = 2131230783;
			
			// aapt resource value: 0x7f08003c
			public const int progressBarEmailSignIn2 = 2131230780;
			
			// aapt resource value: 0x7f08001e
			public const int progressBarLogIn = 2131230750;
			
			// aapt resource value: 0x7f080034
			public const int progressBarSignIn = 2131230772;
			
			// aapt resource value: 0x7f080026
			public const int tab1 = 2131230758;
			
			// aapt resource value: 0x7f080028
			public const int tab2 = 2131230760;
			
			// aapt resource value: 0x7f08002a
			public const int tab3 = 2131230762;
			
			// aapt resource value: 0x7f08002c
			public const int tab4 = 2131230764;
			
			// aapt resource value: 0x7f08002e
			public const int tab5 = 2131230766;
			
			// aapt resource value: 0x7f080030
			public const int textCreateAccount = 2131230768;
			
			// aapt resource value: 0x7f080019
			public const int txtDomoHouse = 2131230745;
			
			// aapt resource value: 0x7f08000a
			public const int txtEmailEditProfile = 2131230730;
			
			// aapt resource value: 0x7f080037
			public const int txtEmailError = 2131230775;
			
			// aapt resource value: 0x7f08001a
			public const int txtEmailLogin = 2131230746;
			
			// aapt resource value: 0x7f080035
			public const int txtEmailRegister = 2131230773;
			
			// aapt resource value: 0x7f08003b
			public const int txtInfoError = 2131230779;
			
			// aapt resource value: 0x7f080018
			public const int txtLuzError = 2131230744;
			
			// aapt resource value: 0x7f08000d
			public const int txtMyInfo = 2131230733;
			
			// aapt resource value: 0x7f080009
			public const int txtNameEditProfile = 2131230729;
			
			// aapt resource value: 0x7f080038
			public const int txtNameRegister = 2131230776;
			
			// aapt resource value: 0x7f08001b
			public const int txtPassLogin = 2131230747;
			
			// aapt resource value: 0x7f080039
			public const int txtPassRegister = 2131230777;
			
			// aapt resource value: 0x7f08001f
			public const int txtPrueba = 2131230751;
			
			// aapt resource value: 0x7f080007
			public const int txtPuertaError = 2131230727;
			
			// aapt resource value: 0x7f080002
			public const int txtServidorError = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FragmentAbout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FragmentCamera = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FragmentConfiguration = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FragmentDoor = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FragmentEditProfile = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int FragmentHouse = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FragmentInfo = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int FragmentLight = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int FragmentMyFriends = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int FragmentMyMicas = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Main = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int MenuSlideTab = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Register = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int RegisterEmail = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int RegisterInfo = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int RegisterPhoto = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int hello = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int CustomActionBarTheme = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int MyActionBar = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int dialog_animation = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
